# Generated by Django 2.2.5 on 2019-09-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190924_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelrecord',
            options={'verbose_name': 'Запись о путешествии', 'verbose_name_plural': 'Записи о путешествиях'},
        ),
        migrations.AlterField(
            model_name='travelimage',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='map.TravelRecord', verbose_name='Путешествие'),
        ),
    ]
