# Generated by Django 2.2.5 on 2019-09-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_travelrecord_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelimage',
            name='text',
        ),
    ]
